### ISSUE TITLE
Offline driver updater not working since "April rebase" release

### ISSUE THREAD

**Issue by Jbrimbelibap** [woa-vayu/Vayu-Drivers#1]
The driver updater script doesn't work anymore, it simply closes straight away after asking for drive letter. No errors given

**Comment by gixousiyq** [comment]
@Jbrimbelibap Do You have NET 8 Runtime installed on your pc?

**Comment by Jbrimbelibap** [comment]
> @Jbrimbelibap Do You have NET 8 Runtime installed on your pc?
I do, had 8.0.3 installed and downloaded and installed the lastest 8.0.5, makes no difference. The old driver updater script also works on my computer. I also tried using Pad 5 to install on vayu, no success either

**Comment by Marius586** [comment]
@Jbrimbelibap Edit script, add pause then run it as administrator, it should show the issue before closing 
P.S. add the word "pause" on a new line at the end, nothing else

**Comment by bibarub** [comment]
you need the **_Desktop_** runtime, by the way
